# Generated by Django 3.1.6 on 2021-06-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
