# Generated by Django 3.1.6 on 2021-06-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
