# Generated by Django 3.1.6 on 2021-06-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210615_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likes',
            new_name='Like',
        ),
    ]
