# Generated by Django 3.1.6 on 2021-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210615_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Action',
        ),
        migrations.AddField(
            model_name='blog',
            name='dislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
