# Generated by Django 3.1.6 on 2021-06-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20210615_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='dislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
