# Generated by Django 3.1.6 on 2021-06-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210616_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='action',
            name='likes',
        ),
    ]
